# frozen_string_literal: true

# Canonical sellers / counterparties (Biedronka, Claude.ai, "Jane Doe").
#
# A Merchant carries the user-facing name, optional logo, a default category
# (used when a transaction's enrichment doesn't override), and provenance:
#   source = "system" — seeded from code
#   source = "user"   — user created it (or accepted an LLM proposal)
#   source = "llm"    — generated by LLM, awaiting approval if confidence is low
#
# `confidence` and `model` are populated only for LLM-sourced merchants — they
# travel with the rule that proposed it.
#
# `archived_at` soft-deletes; transactions retain the merchant_id so historical
# reports keep working.
class CreateMerchants < ActiveRecord::Migration[8.1]
  def change
    create_table :merchants do |t|
      t.references :default_category, foreign_key: { to_table: :categories }
      t.string :name, null: false
      t.string :display_name
      t.string :slug, null: false
      t.string :kind                                # company|person|charity|government|platform
      t.string :logo_url
      t.text   :notes
      t.string :source, null: false                 # system|user|llm
      t.decimal :confidence, precision: 4, scale: 3
      t.string :model
      t.references :approved_by, foreign_key: { to_table: :users }
      t.datetime :approved_at
      t.datetime :archived_at

      t.timestamps
    end

    add_index :merchants, :slug, unique: true
    add_index :merchants, :name
    add_index :merchants, :source
    add_index :merchants, :archived_at
  end
end
