# frozen_string_literal: true

# Canonical seller / counterparty (Biedronka, Claude.ai, "Jane Doe").
#
# Three provenance modes (`source`):
#   "system" — seeded from code, baseline coverage
#   "user"   — created by user, or LLM proposal that user accepted
#   "llm"    — generated by LLM; pending approval if not yet `approved_at`
#
# `default_category` flows through to every transaction enriched against this
# merchant (unless the transaction has its own category override). Changing
# the default retroactively re-categorizes all matching transactions — that's
# the point.
class Merchant < ApplicationRecord
  SOURCES = %w[system user llm].freeze
  KINDS   = %w[company person charity government platform other].freeze

  belongs_to :user
  belongs_to :default_category, class_name: "Category", optional: true
  belongs_to :approved_by, class_name: "User", optional: true
  has_many :merchant_rules, dependent: :destroy
  has_many :transaction_enrichments, dependent: :nullify

  before_validation :generate_slug

  validates :name, presence: true
  validates :slug, presence: true, uniqueness: { scope: :user_id },
                   format: { with: /\A[a-z0-9_\-]+\z/ }
  validates :source, inclusion: { in: SOURCES }
  validates :kind, inclusion: { in: KINDS }, allow_nil: true
  validates :confidence, numericality: { in: 0.0..1.0 }, allow_nil: true

  scope :active,   -> { where(archived_at: nil) }
  scope :archived, -> { where.not(archived_at: nil) }
  scope :approved, -> { where.not(approved_at: nil) }
  scope :pending,  -> { where(source: "llm", approved_at: nil) }
  scope :for_user, ->(user) { where(user_id: user.id) }

  # Thin alias kept so views can call `m.display` without churn. If a real
  # display rule (truncation, sanitization) ever appears, this is the hook.
  def display = name
  def archived? = archived_at.present?
  def approved? = approved_at.present?

  def self.ransackable_attributes(_auth_object = nil)
    %w[id name slug kind source]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[default_category]
  end

  private

  def generate_slug
    return if slug.present?
    return if name.blank?
    base = name.to_s.downcase.gsub(/\p{M}/, "").gsub(/[^a-z0-9]+/, "_").gsub(/_+/, "_").gsub(/\A_|_\z/, "")
    self.slug = base.presence || "merchant_#{SecureRandom.hex(4)}"
  end
end
